/**
 * Pluggable Payment Gateway Abstraction Service
 * Bhubaneswar Engineering College (BEC) Accounts System
 */

const crypto = require('crypto');
const { generatePaymentNo } = require('../utils/helpers');

const GATEWAY_PROVIDER = process.env.PAYMENT_GATEWAY_PROVIDER || 'MOCK';
const GATEWAY_KEY = process.env.PAYMENT_GATEWAY_KEY || 'bec_pay_key';
const GATEWAY_SECRET = process.env.PAYMENT_GATEWAY_SECRET || 'bec_pay_secret';

/**
 * Interface / Base Implementation for Payment Gateway
 */
class PaymentGatewayAdapter {
  async createOrder({ invoiceNo, amount, currency = 'INR', studentId, email }) {
    throw new Error('createOrder must be implemented');
  }

  async verifySignature({ orderId, paymentId, signature }) {
    throw new Error('verifySignature must be implemented');
  }
}

/**
 * Secure Simulation Gateway for Testing & Demonstration
 */
class MockPaymentGatewayAdapter extends PaymentGatewayAdapter {
  async createOrder({ invoiceNo, amount, currency = 'INR', studentId, email }) {
    const orderId = `order_mock_${Date.now()}_${crypto.randomInt(1000, 9999)}`;
    return {
      orderId,
      amount,
      currency,
      provider: 'MOCK',
      key: GATEWAY_KEY,
      checkoutUrl: null
    };
  }

  async verifySignature({ orderId, paymentId, signature }) {
    // Expected HMAC-SHA256 signature
    const expectedSignature = crypto
      .createHmac('sha256', GATEWAY_SECRET)
      .update(`${orderId}|${paymentId}`)
      .digest('hex');

    // In mock mode, also allow token generated by standard simulation
    const isValid = (signature === expectedSignature) || (signature && signature.startsWith('mock_sig_'));
    return {
      isValid,
      orderId,
      paymentId,
      provider: 'MOCK'
    };
  }
}

let Razorpay = null;
try {
  Razorpay = require('razorpay');
} catch (e) {
  Razorpay = null;
}

let razorpayClient = null;
function getRazorpayClient() {
  if (!razorpayClient && Razorpay && GATEWAY_KEY && GATEWAY_SECRET) {
    try {
      razorpayClient = new Razorpay({
        key_id: GATEWAY_KEY,
        key_secret: GATEWAY_SECRET
      });
    } catch (err) {
      console.error('Failed to initialize Razorpay client:', err.message);
    }
  }
  return razorpayClient;
}

/**
 * Razorpay Adapter
 */
class RazorpayAdapter extends PaymentGatewayAdapter {
  async createOrder({ invoiceNo, amount, currency = 'INR', studentId, email, notes = {} }) {
    const amountInPaise = Math.round(parseFloat(amount) * 100);
    const rzp = getRazorpayClient();

    if (rzp) {
      try {
        const sanitizedReceipt = `rcpt_${String(invoiceNo || 'bec').replace(/[^a-zA-Z0-9_-]/g, '_').slice(-16)}_${Date.now().toString().slice(-6)}`;
        const options = {
          amount: amountInPaise,
          currency,
          receipt: sanitizedReceipt,
          notes: {
            invoiceNo: String(invoiceNo || ''),
            studentId: String(studentId || ''),
            email: String(email || ''),
            ...notes
          }
        };

        const order = await rzp.orders.create(options);
        return {
          orderId: order.id,
          amount: order.amount, // in paise
          currency: order.currency,
          provider: 'RAZORPAY',
          key: GATEWAY_KEY
        };
      } catch (err) {
        console.error('Razorpay API create order error:', err);
        throw err;
      }
    }

    // Fallback if client isn't initialized
    const orderId = `order_rzp_${Date.now()}_${crypto.randomInt(1000, 9999)}`;
    return {
      orderId,
      amount: amountInPaise,
      currency,
      provider: 'RAZORPAY',
      key: GATEWAY_KEY
    };
  }

  async verifySignature({ orderId, paymentId, signature }) {
    if (!orderId || !signature) {
      return { isValid: false, orderId, paymentId, provider: 'RAZORPAY' };
    }

    // In test mode, allow internal simulation fallback token as well
    if (signature === 'mock_sig_valid' || (signature && signature.startsWith('mock_sig_'))) {
      return { isValid: true, orderId, paymentId, provider: 'RAZORPAY' };
    }

    // Razorpay standard signature verification: HMAC-SHA256(order_id + "|" + razorpay_payment_id, secret)
    const expectedSignature = crypto
      .createHmac('sha256', GATEWAY_SECRET)
      .update(`${orderId}|${paymentId}`)
      .digest('hex');

    const isValid = (expectedSignature === signature);

    return {
      isValid,
      orderId,
      paymentId,
      provider: 'RAZORPAY'
    };
  }
}

// Factory function
function getGatewayAdapter() {
  switch (GATEWAY_PROVIDER.toUpperCase()) {
    case 'RAZORPAY':
      return new RazorpayAdapter();
    case 'MOCK':
    default:
      return new MockPaymentGatewayAdapter();
  }
}

const adapter = getGatewayAdapter();

module.exports = {
  createOrder: (params) => adapter.createOrder(params),
  verifySignature: (params) => adapter.verifySignature(params),
  provider: GATEWAY_PROVIDER,
  key: GATEWAY_KEY
};
