/**
 * System Constants for Gen-Z University Accounts System
 */

const ROLES = {
  STUDENT: 'STUDENT',
  ACCOUNTS_STAFF: 'ACCOUNTS_STAFF',
  ACCOUNTS_HEAD: 'ACCOUNTS_HEAD',
  ADMIN: 'ADMIN',
  AUDITOR_READ_ONLY: 'AUDITOR_READ_ONLY'
};

const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
};

const PAYMENT_METHODS = {
  ONLINE_GATEWAY: 'ONLINE_GATEWAY',
  CASH: 'CASH',
  CHEQUE: 'CHEQUE',
  DD: 'DD',
  NEFT_RTGS: 'NEFT_RTGS',
  UPI: 'UPI'
};

const REFUND_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROCESSED: 'PROCESSED'
};

const ADJUSTMENT_TYPE = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
};

const RECONCILIATION_STATUS = {
  MATCHED: 'MATCHED',
  UNMATCHED: 'UNMATCHED',
  INVESTIGATION: 'INVESTIGATION',
  RESOLVED: 'RESOLVED'
};

const NOTIFICATION_CATEGORY = {
  INVOICE: 'INVOICE',
  PAYMENT: 'PAYMENT',
  RECEIPT: 'RECEIPT',
  REMINDER: 'REMINDER',
  REFUND: 'REFUND',
  ADJUSTMENT: 'ADJUSTMENT',
  ALERT: 'ALERT'
};

module.exports = {
  ROLES,
  INVOICE_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  REFUND_STATUS,
  ADJUSTMENT_TYPE,
  RECONCILIATION_STATUS,
  NOTIFICATION_CATEGORY
};
